<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

namespace OCBlog\Domain;

class Article {

	/**
	 * 
	 * @var int
	 * @access protected
	 */
	protected  $id;

	/**
	 * 
	 * @var String
	 * @access protected
	 */
	protected  $title;

	/**
	 * 
	 * @var String
	 * @access protected
	 */
	protected  $content;

	/**
	 * 
	 * @var DateTime
	 * @access protected
	 */
	protected  $date_art;


	/**
	 * @access public
	 * @return void
	 */

	public function getId() {

		return $this->id;

	}


	/**
	 * @access public
	 * @param Int $id 
	 * @return Int
	 */

	public function setId($id) {

		$this->id = $id;

	}


	/**
	 * @access public
	 * @param  $ 
	 * @return String
	 */

	public function getTitle() {

		return $this->title;

	}


	/**
	 * @access public
	 * @param  $ 
	 * @param String $title 
	 * @return void
	 */

	public function setTitle($title) {

		$this->title = $title;

	}


	/**
	 * @access public
	 * @return String
	 */

	public function getContent() {

		return $this->content;

	}


	/**
	 * @access public
	 * @param String $content 
	 * @return void
	 */

	public function setContent($content) {

		$this->content = $content,

	}


	/**
	 * @access public
	 * @return DateTime
	 */

	public function getDate() {

		return $this->date_art;

	}


	/**
	 * @access public
	 * @param DateTime $date_art 
	 * @return void
	 */

	public function setDate(DateTime $date_art) {

		$this->date_art = new DateTime();

	}


}
?>